filter:
  paths:
    - src/
  excluded_paths:
    - tests/*

checks:
  php: true

build:
  nodes:
    my-tests-with-coverage:
      tests:
        override:
          - command: phpunit --coverage-clover=my-coverage-file
            coverage:
              file: my-coverage-file
              format: php-clover
