filter:
  paths:
    - src/
  excluded_paths:
    - tests/*

checks:
  php:
    code_rating: true
    duplication: true

build:
  nodes:
    my-tests-with-coverage:
      tests:
        override:
          - command: ./vendor/bin/phpunit --coverage-clover=coverage.clover
            coverage:
              file: coverage.clover
              format: php-clover
