language: php

php:
  # using major version aliases
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer self-update
  - composer install --no-interaction --dev

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

script: ./vendor/bin/phpunit --coverage-clover=coverage.clover

matrix:
  fast_finish: true
